version: "3"

services:
  nginx:
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
      args:
        SSLCRT: ${SSLCRT}
        SSLKEY: ${SSLKEY}
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/conf/:/etc/nginx/http.d/
      - wordpress_data:/var/www/
    networks:
      - inception
    restart: always

  mariadb:
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_PASS: ${DB_PASS}
        DB_USER: ${DB_USER}
        DB_ROOT: ${DB_ROOT}
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: always
  wordpress:
    build:
      context: .
      dockerfile: requirements/wordpress/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        WP_ADMIN: ${WP_ADMIN}
        WP_ADMIN_PASS: ${WP_ADMIN_PASS}
        WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
        WP_USER: ${WP_USER}
        WP_USER_EMAIL: ${WP_USER_EMAIL}
    container_name: wordpress
    depends_on:
      - mariadb
    restart: always
    ports: 
      - "9000:9000"
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/

volumes:
  wordpress_data:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/wordpress

  mariadb_data:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/mariadb

networks:
    inception:
        driver: bridge
