version: "3"
services:
  nginx:  
      build:
        context: ./requirements/nginx
        args:
          SSIGNEDCRT: $SSIGNEDCRT
          SSIGNEDKEY: $SSIGNEDKEY
      env_file:
      - .env
      networks:
        - inception-network
      ports:
        - "443:443"
      restart: on-failure
  mariadb:
      build:
        context: ./requirements/mariadb
      container_name: mariadb
      env_file:
      - .env
      networks:
        - inception-network
      ports:
        - "3306:3306"
networks:
  inception-network:
    name: inception-network
