version: "3"

services:
  nginx:
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/conf/:/etc/nginx/http.d/
      - ./requirements/nginx/tools:/etc/nginx/ssl/
      - wordpress_data:/var/www/
    restart: always

  mariadb:
    build:
      args:
        DB_NAME: ${DB_NAME}
        DB_PASS: ${DB_PASS}
        DB_USER: ${DB_USER}
        DB_ROOT: ${DB_ROOT}
      context: ./requirements/mariadb/.
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always
  wordpress:
    build:
      context: .
      dockerfile: requirements/wordpress/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
    container_name: wordpress
    depends_on:
      - mariadb
    restart: always
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/

volumes:
  wordpress_data:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/wordpress

  mariadb_data:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/mariadb

networks:
    inception:
        driver: bridge
